services:
  - type: web
    name: kuraka-buffer-selector-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"